name: umit
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  equatable: ^1.1.1
  flutter_bloc: ^4.0.0
  meta: ^1.1.8
  shared_preferences: ^0.5.7
  flutter_html: ^0.11.1
  cupertino_icons: ^0.1.2
  youtube_player_flutter: ^6.1.0+7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/presup/illustration.png
    - assets/img/presup/winking-smile.png
    - assets/img/welcome_page/umit.png
    - assets/img/welcome_page/umit-app.png
    - assets/img/welcome_page/hackday2020-logo.png
    - assets/img/welcome_page/background.jpg
    - assets/img/welcome_page/Kids with disabilities.png
    - assets/img/welcome_page/Nick Vuychich.png
    - assets/img/welcome_page/Steven Hocking.png
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-Bold.ttf
